name: code_health_meta
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/DisDis/code_health
author: Igor Demyanov <igor.demyanov@gmail.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
